name: Jeweler

on:
  release:
    types: [ published ]

jobs:
  jeweler:
    uses: tithely/gem-workflows/.github/workflows/jeweler.yml@master
    secrets:
      GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
