# Builds and pushes a gem to RubyGems.
name: RubyGems

on:
  pull_request:
    # Only on the production branch
    branches:
      - production
    # Only when closed
    types:
      - closed
  workflow_dispatch:

jobs:
  push:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    # If you configured a GitHub environment on RubyGems, you must use it here.
    environment: release

    steps:
      # Set up
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ruby

      # Release
      - uses: rubygems/release-gem@v1
