name: Tester

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake
